import type { FoodItem } from "@/lib/nutrition-data"

/**
 * Base de données tunisienne 🇹🇳
 *
 * Pour ajouter un plat : ajoute une entrée à `tunisianFoods` ci-dessous en
 * respectant le type `TunisianFood` (id unique préfixé `tn_`, macros pour LA
 * portion indiquée dans `serving`). La recherche de l'écran Food fusionne
 * automatiquement cette liste avec la base générale — rien d'autre à modifier.
 */

export type TunisianCategory =
  | "plats" // couscous, tajine, mloukhia…
  | "entrees" // briks, salades, chakchouka…
  | "rue" // street food : kafteji, fricassé, bambalouni…
  | "douceurs" // makroudh, ka'ak warka, assida…
  | "boissons" // thé à la menthe, café turc…

export type TunisianFood = FoodItem & {
  category: TunisianCategory
  /** alias de recherche (français, arabe translittéré) — optionnel */
  aliases?: string[]
}

export const tunisianCategoryMeta: Record<TunisianCategory, { label: string; emoji: string }> = {
  plats: { label: "Plats tunisiens", emoji: "🍲" },
  entrees: { label: "Entrées & salades", emoji: "🥗" },
  rue: { label: "Street food", emoji: "🥙" },
  douceurs: { label: "Douceurs", emoji: "🍮" },
  boissons: { label: "Boissons", emoji: "🫖" },
}

export const tunisianFoods: TunisianFood[] = [
  // ------------------------------------------------------------------ plats
  {
    id: "tn_couscous_poulet",
    name: "Couscous au poulet",
    serving: "1 assiette (350 g)",
    calories: 620,
    protein: 38,
    carbs: 78,
    fat: 16,
    emoji: "🍲",
    category: "plats",
    aliases: ["kosksi", "كوسكسي"],
  },
  {
    id: "tn_couscous_agneau",
    name: "Couscous à l'agneau",
    serving: "1 assiette (380 g)",
    calories: 720,
    protein: 40,
    carbs: 80,
    fat: 26,
    emoji: "🍲",
    category: "plats",
    aliases: ["kosksi ghallaba", "couscous mouton"],
  },
  {
    id: "tn_couscous_poisson",
    name: "Couscous au poisson",
    serving: "1 assiette (360 g)",
    calories: 580,
    protein: 36,
    carbs: 74,
    fat: 14,
    emoji: "🐟",
    category: "plats",
    aliases: ["couscous poisson", "kosksi 7out"],
  },
  {
    id: "tn_couscous_veg",
    name: "Couscous aux légumes",
    serving: "1 assiette (300 g)",
    calories: 420,
    protein: 12,
    carbs: 78,
    fat: 8,
    emoji: "🥕",
    category: "plats",
    aliases: ["couscous légumes"],
  },
  {
    id: "tn_mloukhia",
    name: "Mloukhia (veau)",
    serving: "1 bol (300 g)",
    calories: 480,
    protein: 34,
    carbs: 18,
    fat: 30,
    emoji: "🥘",
    category: "plats",
    aliases: ["ملوخية", "mulukhiyah"],
  },
  {
    id: "tn_tajine_tunisien",
    name: "Tajine tunisien (poulet)",
    serving: "1 part (250 g)",
    calories: 460,
    protein: 28,
    carbs: 22,
    fat: 28,
    emoji: "🥧",
    category: "plats",
    aliases: ["tajine tounsi", "طاجين"],
  },
  {
    id: "tn_ojja_merguez",
    name: "Ojja merguez",
    serving: "1 poêle (350 g)",
    calories: 640,
    protein: 30,
    carbs: 16,
    fat: 50,
    emoji: "🍳",
    category: "plats",
    aliases: ["ojja", "عجة"],
  },
  {
    id: "tn_ojja_crevettes",
    name: "Ojja crevettes",
    serving: "1 poêle (320 g)",
    calories: 380,
    protein: 32,
    carbs: 14,
    fat: 22,
    emoji: "🍤",
    category: "plats",
    aliases: ["ojja gambas"],
  },
  {
    id: "tn_kamounia",
    name: "Kamounia (veau au cumin)",
    serving: "1 bol (280 g)",
    calories: 430,
    protein: 32,
    carbs: 20,
    fat: 24,
    emoji: "🥘",
    category: "plats",
    aliases: ["كمونية"],
  },
  {
    id: "tn_chorba_frik",
    name: "Chorba frik",
    serving: "1 bol (300 ml)",
    calories: 210,
    protein: 12,
    carbs: 28,
    fat: 6,
    emoji: "🍜",
    category: "plats",
    aliases: ["soupe frik", "شربة فريك"],
  },
  {
    id: "tn_lablabi",
    name: "Lablabi",
    serving: "1 bol (450 g)",
    calories: 520,
    protein: 20,
    carbs: 68,
    fat: 18,
    emoji: "🥣",
    category: "plats",
    aliases: ["لبلابي", "leblebi"],
  },

  // ---------------------------------------------------------------- entrées
  {
    id: "tn_brik_oeuf",
    name: "Brik à l'œuf",
    serving: "1 pièce (110 g)",
    calories: 310,
    protein: 12,
    carbs: 24,
    fat: 19,
    emoji: "🥟",
    category: "entrees",
    aliases: ["brika", "بريك"],
  },
  {
    id: "tn_brik_thon",
    name: "Brik au thon",
    serving: "1 pièce (120 g)",
    calories: 340,
    protein: 15,
    carbs: 26,
    fat: 20,
    emoji: "🥟",
    category: "entrees",
    aliases: ["brik thon"],
  },
  {
    id: "tn_salade_mechouia",
    name: "Salade méchouia",
    serving: "1 assiette (180 g)",
    calories: 140,
    protein: 3,
    carbs: 14,
    fat: 9,
    emoji: "🫑",
    category: "entrees",
    aliases: ["slata mechouia", "مشوية"],
  },
  {
    id: "tn_chakchouka",
    name: "Chakchouka",
    serving: "1 poêle (300 g)",
    calories: 320,
    protein: 16,
    carbs: 18,
    fat: 22,
    emoji: "🍅",
    category: "entrees",
    aliases: ["chakchuka", "شكشوكة"],
  },
  {
    id: "tn_salade_tunisienne",
    name: "Salade tunisienne",
    serving: "1 assiette (200 g)",
    calories: 110,
    protein: 2,
    carbs: 12,
    fat: 6,
    emoji: "🥗",
    category: "entrees",
    aliases: ["slata tounsiya"],
  },
  {
    id: "tn_ftat",
    name: "Ftat (pains épicés en sauce)",
    serving: "1 bol (300 g)",
    calories: 450,
    protein: 14,
    carbs: 52,
    fat: 20,
    emoji: "🍞",
    category: "entrees",
    aliases: ["fatat"],
  },
  {
    id: "tn_assida",
    name: "Assida (au miel)",
    serving: "1 bol (250 g)",
    calories: 520,
    protein: 8,
    carbs: 98,
    fat: 10,
    emoji: "🍮",
    category: "entrees",
    aliases: ["عصيدة"],
  },
  {
    id: "tn_harissa",
    name: "Harissa maison",
    serving: "1 c. à soupe (20 g)",
    calories: 25,
    protein: 1,
    carbs: 4,
    fat: 1,
    emoji: "🌶️",
    category: "entrees",
    aliases: ["هريسة"],
  },

  // ------------------------------------------------------------- street food
  {
    id: "tn_kafteji",
    name: "Kafteji",
    serving: "1 galette (300 g)",
    calories: 620,
    protein: 14,
    carbs: 52,
    fat: 40,
    emoji: "🥙",
    category: "rue",
    aliases: ["كفتاجي"],
  },
  {
    id: "tn_fricasse",
    name: "Fricassé au thon",
    serving: "1 pièce (130 g)",
    calories: 380,
    protein: 12,
    carbs: 38,
    fat: 20,
    emoji: "🥖",
    category: "rue",
    aliases: ["fricassi"],
  },
  {
    id: "tn_mlawi",
    name: "Mlawi",
    serving: "1 pièce (120 g)",
    calories: 330,
    protein: 7,
    carbs: 44,
    fat: 14,
    emoji: "🫓",
    category: "rue",
    aliases: ["ملوي", "mlouwi"],
  },
  {
    id: "tn_msemen",
    name: "Msemen",
    serving: "1 pièce (110 g)",
    calories: 300,
    protein: 6,
    carbs: 40,
    fat: 13,
    emoji: "🫓",
    category: "rue",
    aliases: ["مسمن"],
  },
  {
    id: "tn_bambalouni",
    name: "Bambalouni",
    serving: "1 pièce (90 g)",
    calories: 290,
    protein: 3,
    carbs: 34,
    fat: 15,
    emoji: "🍩",
    category: "rue",
    aliases: ["bambalouni sucré", "بمبالوني"],
  },
  {
    id: "tn_kafteji_viande",
    name: "Kafteji avec viande",
    serving: "1 galette (350 g)",
    calories: 720,
    protein: 26,
    carbs: 54,
    fat: 46,
    emoji: "🥙",
    category: "rue",
    aliases: ["kafteji all Viande"],
  },
  {
    id: "tn_kaftagi_oeuf",
    name: "Kafteji avec œuf",
    serving: "1 galette (330 g)",
    calories: 680,
    protein: 20,
    carbs: 54,
    fat: 44,
    emoji: "🍳",
    category: "rue",
    aliases: [],
  },

  // --------------------------------------------------------------- douceurs
  {
    id: "tn_makroudh",
    name: "Makroudh (dattes)",
    serving: "1 pièce (60 g)",
    calories: 210,
    protein: 3,
    carbs: 34,
    fat: 7,
    emoji: "🍯",
    category: "douceurs",
    aliases: ["makroud", "مقروض"],
  },
  {
    id: "tn_kaak_warka",
    name: "Ka'ak warka",
    serving: "1 pièce (45 g)",
    calories: 180,
    protein: 3,
    carbs: 26,
    fat: 8,
    emoji: "🍪",
    category: "douceurs",
    aliases: ["kaak warka", "كاعك ورقة"],
  },
  {
    id: "tn_baklawa",
    name: "Baklawa tunisienne",
    serving: "1 part (70 g)",
    calories: 300,
    protein: 5,
    carbs: 34,
    fat: 17,
    emoji: "🥮",
    category: "douceurs",
    aliases: ["baklava"],
  },
  {
    id: "tn_ghriba",
    name: "Ghriba (amande)",
    serving: "1 pièce (35 g)",
    calories: 150,
    protein: 3,
    carbs: 18,
    fat: 8,
    emoji: "🍪",
    category: "douceurs",
    aliases: ["غريبة"],
  },

  // --------------------------------------------------------------- boissons
  {
    id: "tn_the_menthe",
    name: "Thé à la menthe",
    serving: "1 verre (150 ml)",
    calories: 60,
    protein: 0,
    carbs: 15,
    fat: 0,
    emoji: "🫖",
    category: "boissons",
    aliases: ["atay", "أتاي"],
  },
  {
    id: "tn_cafe_turc",
    name: "Café turc",
    serving: "1 tasse (80 ml)",
    calories: 25,
    protein: 0,
    carbs: 5,
    fat: 0,
    emoji: "☕",
    category: "boissons",
    aliases: ["kahwa", "قهوة"],
  },
  {
    id: "tn_cafe_express",
    name: "Express (café tunisien)",
    serving: "1 tasse (60 ml)",
    calories: 5,
    protein: 0,
    carbs: 1,
    fat: 0,
    emoji: "☕",
    category: "boissons",
    aliases: ["express"],
  },
  {
    id: "tn_citronnade",
    name: "Citronnade (chia)",
    serving: "1 verre (250 ml)",
    calories: 90,
    protein: 0,
    carbs: 22,
    fat: 0,
    emoji: "🍋",
    category: "boissons",
    aliases: ["citron b'bidha", "لمون بالبيضة"],
  },
]

/** Search across names + aliases (accent/case-insensitive). */
export function searchTunisianFoods(query: string): TunisianFood[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  return tunisianFoods.filter((f) => {
    if (f.name.toLowerCase().includes(q)) return true
    return (f.aliases ?? []).some((a) => a.toLowerCase().includes(q))
  })
}
